# 目的：了解Python基本語法

1. [資料型別](#01)
2. [for-loop](#02)
3. [while-loop](#03)
4. [清單(list)](#04)
5. [tuple是什麼？](#05)
6. [Python特殊的清單處理方式](#06)
7. [if的用法](#07)
8. [以if控制迴圈的break和continue](#08)
9. [函數：將計算結果直接於函數內印出或回傳(return)出函數外](#09)
10. [匿名函數](#10)
11. [物件導向範例](#11)
12. [NumPy (Python中用於處理numerical array的套件)](#12)
13. [一維序列](#13)
14. [二維矩陣](#14)

# 練習

* [運用range(5),for以及append()建立一清單，其內容為\[0,1,4,9,16\] ](#ex01)
* [運用range(5), if以及for建立一清單，其內容為\[0,4,16\] ](#ex02)
* [試輸出99乘法表](#ex1)
* [試輸出99乘法表(以清單表示)](#ex2)
* [寫一個函數factorial(n)。](#ex3)
* [建立一函數 f。輸入: 一個 2 維矩陣，輸出: 該2維矩陣內的所有數值加總。](#ex4)


---

## <a id="01"/>資料型別

### 整數(int)

In [1]:
a=1

In [2]:
type(a)

int

In [3]:
b=3

In [4]:
type(b)

int

兩整數相除，輸出結果為浮點數(float)。(備註：Python 3開始)

In [5]:
a/b

0.3333333333333333

In [6]:
type(a/b)

float

在Python3，兩整數相除，需以//運算子來相除，方能真正用整數儲存該結果。

In [7]:
a//b

0

In [8]:
type(a//b)

int

兩整數相加，其輸出仍然為整數。

In [9]:
a+b

4

In [10]:
type(a+b)

int

### 浮點數(float)

Python不需宣告型別。一個數字將會被判別為整數(int)或浮點數(float)，需看該數是否有小數點存在。

In [11]:
type(1)

int

In [12]:
type(1.)

float

In [13]:
type(1.E-5)

float

### 字串(str)

In [14]:
mystr='Hello World!'

In [15]:
type(mystr)

str

將該字串所有字變成大寫

In [16]:
mystr.upper()

'HELLO WORLD!'

將該字串所有字變成小寫

In [17]:
mystr.upper().lower()

'hello world!'

取出該字串前三個字

In [18]:
mystr[0:3]

'Hel'

檢查某字串片段是否存在於該字串

In [19]:
'Wor' in mystr

True

In [20]:
'WOR' in mystr

False

In [21]:
'WOR' in mystr.upper()

True

以len()看字串長度

In [22]:
len(mystr)

12

In [23]:
mystr='   hi   '

清除左右空白

In [24]:
mystr.strip()

'hi'

清除左空白

In [25]:
mystr.lstrip()

'hi   '

清除右空白

In [26]:
mystr.rstrip()

'   hi'

置換字串內的h成f

In [27]:
mystr.replace('h','f')

'   fi   '

### 布林(Boolean)

In [28]:
t=True #真
f=False #假

In [29]:
t==f  #真等於假？

False

In [30]:
t==t  #真等於真？

True

In [31]:
t!=f  #真不等於假？

True

In [32]:
t==f or t!=f   #真等於假 或是 真不等於假？

True

In [33]:
t==f and t!=f  #真等於假 和 真不等於假？

False

In [34]:
not t  #非真？

False

[回索引](#目的：了解Python基本語法)

## <a id="02"/>for-loop

In [35]:
for j in range(5):
    print(j)

0
1
2
3
4


以上，我們使用了range()這個內建函數，它到底是什麼？

In [36]:
r=range(5)
print( type(r) )

<class 'range'>


用type()檢查變數r的型別，我們發現了r=range(5)是屬於'range'這個類別的一個物件。

接下來，我們以內建函數hasattr()去檢查range(5)這個物件是不是可疊代(iterable):

首先以help()函數檢查一下hasattr()的用法：

In [37]:
help(hasattr)

Help on built-in function hasattr in module builtins:

hasattr(obj, name, /)
    Return whether the object has an attribute with the given name.
    
    This is done by calling getattr(obj, name) and catching AttributeError.



In [38]:
hasattr(range(5), '__iter__')

True

In [39]:
r=range(5).__iter__()        # 取得range(5)的疊代器
print( r.__next__() )        # 進行疊代並印出
print( r.__next__() )        # 進行疊代並印出
print( r.__next__() )        # 進行疊代並印出
print( r.__next__() )        # 進行疊代並印出
print( r.__next__() )        # 進行疊代並印出
print( r.__next__() )        # 進行疊代並印出

0
1
2
3
4


StopIteration: 

### 小結

1. 若物件(object)為可疊代(iterable)：
	* 表示我們可用\_\_iter\_\_()以及\_\_next\_\_()來操控該物件，一個一個的去取得物件裡面的元素。
	* 物件裡面的元素亦可簡單的以for迴圈來取得。
2. 複習以下函數的意義：hasattr(),\_\_iter\_\_(),\_\_next\_\_(),range()

[回索引](#目的：了解Python基本語法)

-----

## <a id="03"/> while-loop

In [40]:
i=0
while(i<5):
    print(i)
    i+=1      # i=i+1的簡寫

0
1
2
3
4


常用於不確定要跑幾次，要跑到直到條件滿足才跳出迴圈的情形。例如：嘗試擷取某網頁，直到失敗次數太多或是擷取成功為止。

[回索引](#目的：了解Python基本語法)

## <a id="04"/>清單(list)

定義：包含元素的一個集合。清單內的元素可重複，且每個元素都有一個索引(index)。

In [41]:
array=[1,2,2,3,4,5]  #建立一個清單
print(array)
print(array[0])      #印出清單內的第一個元素
print(array[-1])     #印出清單內最後一個元素

[1, 2, 2, 3, 4, 5]
1
5


In [42]:
type([1,2,2,3,4,5]) #以type查看清單型別，確定清單(list)的型別就是list。

list

In [43]:
hasattr([1,2,3,4,5],'__iter__') # 若是[1,2,3,4,5]為可疊代物件，那我們就可以用迴圈來疊代出清單內的所有元素。

True

In [44]:
for j in [1,2,3,4,5]:
    print(j,j**2)

1 1
2 4
3 9
4 16
5 25


In [45]:
for j in [1,2.,'字串',3,range(10),5,[1,1,1,2,2,2]]:
    print(j,'\t',type(j),'\t',hasattr(j,'__iter__'))

1 	 <class 'int'> 	 False
2.0 	 <class 'float'> 	 False
字串 	 <class 'str'> 	 True
3 	 <class 'int'> 	 False
range(0, 10) 	 <class 'range'> 	 True
5 	 <class 'int'> 	 False
[1, 1, 1, 2, 2, 2] 	 <class 'list'> 	 True


從以上得知：
1. 清單裡的元素可以有不同的型別(type)。
2. 字串(str)和清單(list)一樣，是可以疊代的物件。因此，他們可以用for迴圈來進行內容的提取，例如：

In [46]:
for j in 'Python':
    print(j)

P
y
t
h
o
n


使用append()添加新元素至清單內

In [47]:
array=[1,2,3]
array.append(4)
print(array)

[1, 2, 3, 4]


使用del 刪除清單內元素

In [48]:
print(array)
del array[2]  #刪除清單內的第二個元素
print(array)

[1, 2, 3, 4]
[1, 2, 4]


我們可使用len()去得知清單的長度

In [49]:
array=[10,20,30,40]
print(len(array))

4


使用enumerate()去列舉清單

In [50]:
enumerate(array)

In [51]:
type(enumerate(array))

enumerate

In [52]:
hasattr(enumerate,'__iter__')

True

In [53]:
for j in enumerate(array):
    print(j)

(0, 10)
(1, 20)
(2, 30)
(3, 40)


In [54]:
print(  type( (0,10) ) )

<class 'tuple'>


[回索引](#目的：了解Python基本語法)

## <a id="05"/>tuple是什麼？

In [55]:
array=(1,2,3,"abc")
print(array)

(1, 2, 3, 'abc')


In [56]:
del array[1]

TypeError: 'tuple' object doesn't support item deletion

In [57]:
array.append(5)

AttributeError: 'tuple' object has no attribute 'append'

In [58]:
array[2]=0

TypeError: 'tuple' object does not support item assignment

結論：不可新增刪除覆蓋tuple內的元素，因此tuple可以被看做是唯讀的list。

list可以被取set()。

set的定義：集合內元素不允許重複，且集合內的元素無索引。

In [59]:
set([1,1,2,3,3,4,1,2,'alpha','beta'])

{1, 2, 3, 4, 'alpha', 'beta'}

In [60]:
type( {1, 2, 3, 4, 'beta', 'alpha'} )

set

In [61]:
st={1,1,2,3,3,4,1,2,'alpha','beta'}
print(st)
print(hasattr(st,'__iter__'))

{1, 2, 3, 4, 'alpha', 'beta'}
True


In [62]:
for j in st:
    print(j)

1
2
3
4
alpha
beta


In [63]:
print(st[0])

TypeError: 'set' object does not support indexing

也就是先前說的，set內的元素並無索引。

[回索引](#目的：了解Python基本語法)

## <a id="06"/>Python特殊的清單處理方式

將range(5)裡面的東西抓出來，放到一清單叫做lst，可有各種寫法：

第一種

In [64]:
lst=[]
for j in range(5):
    lst.append(j)
print(lst)

[0, 1, 2, 3, 4]


第二種

In [65]:
lst=[j for j in range(5)]   #此是非常Python的寫法(Pythonic way of coding)
print(lst)

[0, 1, 2, 3, 4]


第三種

In [66]:
lst=list(range(5))
print(lst)

[0, 1, 2, 3, 4]


第四種

In [67]:
lst=[*range(5)]
print(lst)

[0, 1, 2, 3, 4]


## <a id="ex01" style='color:purple'/> 練習0-1. 運用range(5),for以及append()建立一清單，其內容為[0,1,4,9,16]

In [ ]:
#法一：
lst=[]
for j in range(5):
    #完成接下來的部分

In [ ]:
#法二：
#提示： lst=[.....]

[回索引](#目的：了解Python基本語法)

##  <a id="ex02" style='color:purple'/> 練習0-2. 運用range(5), if以及for建立一清單，其內容為[0,4,16]

In [ ]:
# 法一：
lst=[]
for j in range(5):
    #完成接下來的部分

In [ ]:
#法二：
#提示： lst=[.....]

[回索引](#目的：了解Python基本語法)

## <a id="07"/>if的用法

### if...elif..else的使用 :

In [68]:
x=5

if(x==1):
    print('x is 1')
elif(x==2):
    print('x is 2')
else:
    print('x is neither 1 nor 2.')

x is neither 1 nor 2.


### 例：取range(10)內的偶數並印出：

法一

In [69]:
for j in range(10):
    if(j%2==0):
        print(j)

0
2
4
6
8


法二

In [70]:
[j for j in range(10) if j%2==0]

[0, 2, 4, 6, 8]

[回索引](#目的：了解Python基本語法)

## <a id="08"/>以if控制迴圈的break和continue

In [71]:
for j in range(5):
    print(j)
    if(j==2):
        break      #中斷，跳出迴圈

0
1
2


In [72]:
for j in range(5):
    if(j==2):
        continue  #略過以下程式碼，並繼續疊代至下一個元素
    print(j)

0
1
3
4


[回索引](#目的：了解Python基本語法)

##  <a id="ex1" style='color:purple'/> 練習1. 試著輸出以下內容

In [ ]:
#提示：使用for, range(),print()

for i in range(1,4):
    #完成接下來的部分

[回索引](#目的：了解Python基本語法)

##  <a id="ex2" style='color:purple'/> 練習2. 試著輸出以下內容

In [ ]:
#提示：使用for, range(),print()，以及建立一個清單(list)
#完成接下來的部分

[回索引](#目的：了解Python基本語法)

## <a id="09"/>函數：將計算結果直接於函數內印出或回傳(return)出函數外

### 例一

In [73]:
def square(x):
    print(x*x)

In [74]:
def square_return(x):
    return(x**2)

square(x)將只會印出x, 而square_return(x)將會回傳x。

In [75]:
square(2)

4


In [76]:
square_return(2)

4

可另一變數res接收square_return(x)回傳的值。

In [77]:
res=square_return(2)

In [78]:
print(res)

4


需注意的是，square(x)並不會回傳值，因此res將接收到None(無)。

In [79]:
res=square(2)

4


In [80]:
print(res)

None


### 例二： 寫一個函數add(a, b)。其輸入為 a和b，輸出為 a+b。

In [81]:
def add(a,b):
    return a+b

In [82]:
addResult=add(5,7)
print(addResult)

12


### 複習：Java函數寫法(輸入x，回傳x平方)

In [83]:
%%file testSquare.java
public class testSquare{
    public static void main(String args[]){
        int y=square(2);
        System.out.println(y);
    }
    
    static int square(int x){
        return x*x;
    }
}

Writing testSquare.java


In [84]:
!javac testSquare.java
!java testSquare

4


[回索引](#目的：了解Python基本語法)

## <a id="ex3" style='color:purple'/> 練習3：寫一個函數factorial(n)。

其作用為：

輸入：$n$，輸出：$1*2*3*....*n$

In [ ]:
# 修改以下程式碼，以完成函數factorial(n)
def factorial(n):
    if(n==0):
        return ???
    if(n!=0):
        return ???

[回索引](#目的：了解Python基本語法)

## <a id="10"/>匿名函數

一般函數寫法

In [86]:
def f(x,y):
    return x+y

In [87]:
f(1,2)

3

使用匿名函數，並將匿名函數給予名稱f。此方法得到的函數等同於上述使用一般函數寫法的結果。

In [88]:
f=lambda x,y:x+y

In [89]:
f(1,2)

3

將匿名函數直接拿來使用，不給名稱，用完就丟。

In [90]:
(lambda x,y:x+y)(1,2)  # 1+2=3

3

In [91]:
(lambda x:x*x)(7)      # 7X7=49

49

[回索引](#目的：了解Python基本語法)

## <a id="11"/> 物件導向範例

範例：提款機

In [92]:
class Customer(object):
    def __init__(self, name, balance=0.0):
        self.name=name             #當物件被新建立，姓名以及餘額兩個屬性將被初始化
        self.balance=balance

    def withdraw(self, amount):    #提款
        if amount > self.balance:  #若要提取大於帳戶餘額的數目，將提出錯誤訊息
            raise RuntimeError('Amount greater than available balance.')
        self.balance -= amount
        return self.balance
    
    def deposit(self, amount):     #存款
        self.balance += amount
        return self.balance

* 第1行：所有Python3類別都是object這個類別的子類別。
* 第2行：當物件產生時，初始子__init__()(等同Java中的建構子)將初始化屬於該物件的一些屬性。此範例中，屬於該物件的兩個屬性，也就是人名和帳戶餘額將被建立。
* 所有方法都要接收物件本身為第一個參數。依照慣例，大家將該物件本身稱作self。

In [93]:
a=Customer("Bill",100)
a.withdraw(70)

30

In [94]:
a.deposit(60)

90

In [95]:
a.withdraw(100)

RuntimeError: Amount greater than available balance.

[回索引](#目的：了解Python基本語法)

---

## <a id="12"/>NumPy (Python中用於處理numerical array的套件)

此套件用於建立數值陣列和做數值運算。

https://docs.scipy.org/doc/numpy/reference/index.html

In [96]:
import numpy as np

內建常數$\pi$

In [97]:
np.pi

3.141592653589793

計算根號$\pi$

In [98]:
np.sqrt(np.pi)

1.7724538509055159

[回索引](#目的：了解Python基本語法)

## <a id="13"/>一維序列

用np.arange(n)建立一序列內容為[0 1 2 .....n-1]

In [99]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

用np.linspace(0,2.*np.pi,10)建立一個一維線性空間。起始為0，終點為 $\pi$ ，共10個點。

In [100]:
np.linspace(0,2.*np.pi,10)

array([ 0.        ,  0.6981317 ,  1.3962634 ,  2.0943951 ,  2.7925268 ,
        3.4906585 ,  4.1887902 ,  4.88692191,  5.58505361,  6.28318531])

將數列內所有數值+100

In [101]:
np.arange(10)+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

將數列內所有數值取平方

In [102]:
np.arange(10)**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

以np.mean()計算出算數平均

In [103]:
np.mean( np.arange(10) )

4.5

以np.std()計算出標準差

In [104]:
np.std( np.arange(10) )

2.8722813232690143

[回索引](#目的：了解Python基本語法)

## <a id="14"/>二維矩陣

建立一矩陣

In [105]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [106]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

將$A$轉置 ($A^{T}$)

In [107]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

$A\cdot A^{T}$

In [108]:
A.dot(A.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

以A[位置1][位置2]取出二維陣列$A$的部分片段。 其中[位置1]指定了第幾列，[位置2]指定了第幾行。

In [109]:
A[0]

array([1, 2, 3])

In [110]:
A[2][1:3]

array([8, 9])

In [111]:
A[:][1:3]

array([[4, 5, 6],
       [7, 8, 9]])

檢查一下A的形狀

In [112]:
A.shape

(3, 3)

以條件找尋A裡面符合條件的數值

In [113]:
A>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [114]:
A[A>5]

array([6, 7, 8, 9])

[回索引](#目的：了解Python基本語法)

## <a id="ex4" style='color:purple'/>練習4: 建立一函數 f。輸入: 一個 2 維矩陣，輸出: 該2維矩陣內的所有數值加總。

In [115]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
def f(A)
    # 完成此函數
    return ???

[回索引](#目的：了解Python基本語法)