Ex1.

In [1]:
for j in range(1,4):
    for k in range(1,6):
        print(j,k,j*k)
    print()

1 1 1
1 2 2
1 3 3
1 4 4
1 5 5

2 1 2
2 2 4
2 3 6
2 4 8
2 5 10

3 1 3
3 2 6
3 3 9
3 4 12
3 5 15



Ex2. Sol1.

In [2]:
for i in range(1,10):
    lst=[]
    for j in range(1,10):
        lst.append(i*j)
    print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 4, 6, 8, 10, 12, 14, 16, 18]
[3, 6, 9, 12, 15, 18, 21, 24, 27]
[4, 8, 12, 16, 20, 24, 28, 32, 36]
[5, 10, 15, 20, 25, 30, 35, 40, 45]
[6, 12, 18, 24, 30, 36, 42, 48, 54]
[7, 14, 21, 28, 35, 42, 49, 56, 63]
[8, 16, 24, 32, 40, 48, 56, 64, 72]
[9, 18, 27, 36, 45, 54, 63, 72, 81]


Ex2. Sol2.

In [3]:
for i in range(1,10):
    lst=[i*j for j in list(range(1,10))]
    print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 4, 6, 8, 10, 12, 14, 16, 18]
[3, 6, 9, 12, 15, 18, 21, 24, 27]
[4, 8, 12, 16, 20, 24, 28, 32, 36]
[5, 10, 15, 20, 25, 30, 35, 40, 45]
[6, 12, 18, 24, 30, 36, 42, 48, 54]
[7, 14, 21, 28, 35, 42, 49, 56, 63]
[8, 16, 24, 32, 40, 48, 56, 64, 72]
[9, 18, 27, 36, 45, 54, 63, 72, 81]


Ex2. Sol3.

In [4]:
lst=list(range(1,10))
for k in range(1,10):
        print(list(map( (lambda x:k*x) ,lst)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 4, 6, 8, 10, 12, 14, 16, 18]
[3, 6, 9, 12, 15, 18, 21, 24, 27]
[4, 8, 12, 16, 20, 24, 28, 32, 36]
[5, 10, 15, 20, 25, 30, 35, 40, 45]
[6, 12, 18, 24, 30, 36, 42, 48, 54]
[7, 14, 21, 28, 35, 42, 49, 56, 63]
[8, 16, 24, 32, 40, 48, 56, 64, 72]
[9, 18, 27, 36, 45, 54, 63, 72, 81]


Ex2. Sol4.

In [5]:
import numpy as np
for j in range(1,10):
    print(j*np.linspace(1,9,9))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   4.   6.   8.  10.  12.  14.  16.  18.]
[  3.   6.   9.  12.  15.  18.  21.  24.  27.]
[  4.   8.  12.  16.  20.  24.  28.  32.  36.]
[  5.  10.  15.  20.  25.  30.  35.  40.  45.]
[  6.  12.  18.  24.  30.  36.  42.  48.  54.]
[  7.  14.  21.  28.  35.  42.  49.  56.  63.]
[  8.  16.  24.  32.  40.  48.  56.  64.  72.]
[  9.  18.  27.  36.  45.  54.  63.  72.  81.]
